from .entrenamiento import CrearEntrenamientoV
from .plan import CrearPlanV
from .perfil import CrearPerfilV
from .auth_view import CrearAuthV
from .ejecutar_rutina import CrearEjecutarRutinaV
from .ejercicios import CrearEjerciciosV
from .crear_rutina_manual import CrearRutinaManualV
from .estadisticas import CrearEstadisticasV
from .generar_automatica import CrearGenerarAutomaticaV
from .editar_perfil import CrearEditarPerfilV   